// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

//import MessageSubscriptionController from "./message_subscription_controller"
//application.register("message-subscription", MessageSubscriptionController)

import RealtySubscriptionController from "./realty_subscription_controller"
application.register("realty-subscription", RealtySubscriptionController)
